version: "3.9"
services:
  website:
    build: .
    ports:
      - "12000:3000"
    env_file:
      - .env
    depends_on:
      - db
    links:
      - db
    restart: always

  db:
    image: postgres:14
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", 'pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"']
      interval: 60s
      timeout: 5s
      retries: 5
    restart: always

  prisma-studio:
    image: timothyjmiller/prisma-studio:latest
    restart: always
    env_file:
     - .env
#    ports:
#      - "12001:5555"
    depends_on:
      - db
    links:
      - db

volumes:
  database:
